- name: Clean TF cache
  hosts: localhost,all
  tasks:
    - name: Clean TF cache
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "log.txt"
        - "blockscout-*"
        - "/tmp/files-*"